### ISSUE TITLE
Resource.parse() assertionMethods resolves to null 

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/tbdex-kt#65]
Call stack: `Resource.parse("{some-json-string}")` 👉 `CryptoUtils.verify()` 👉  `didResolutionResult.didDocument.assertionMethodVerificationMethodsDereferenced` resolves to `null`

---

I'm out of my depth here, but running into a null reference issue. I'm using [`tbdex-mock-pfi`](https://github.com/TBD54566975/tbdex-mock-pfi) to stand up an HTTP endpoint to `GET /offerings`, and then I'm taking that _Offering_ and running it through `Resource.parse()` in this repo (`tbdex-kt`). The final exception thrown is this...

```
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "assertionMethods" is null
```

But, more precisely, the cause is the `assertionMethods` variable resolves to a `null` value, from this [line of code](https://github.com/TBD54566975/tbdex-kt/blob/fea1c31d94dae7d131022165552a4160772c4574/protocol/src/main/kotlin/tbdex/sdk/protocol/CryptoUtils.kt#L54)

```kotlin
val assertionMethods = didResolutionResult.didDocument.assertionMethodVerificationMethodsDereferenced
```

---

This may be an issue with the resource being built by `tbdex-mock-pfi` and nothing wrong with `tbdex-kt` whatsoever

---

I wrote a sample test case to illustrate the point, you can find it on [the branch `kendallw.resource-parse-did-bug` here](https://github.com/TBD54566975/tbdex-kt/blob/39b2a341bcb85d71e487834009fa69724d7e8c5b/protocol/src/test/kotlin/tbdex/sdk/protocol/CryptoUtilsTest.kt#L9). But, I had to pull `web5-kt` from my `mavenLocal()` in order to illustrate it, because the latest `web5-kt` isn't published as a package (and it's needed here).

Sample Resource JSON string here

```json
  {
    "metadata": {
      "from": "did:ion:EiBZ4JrUCtDbcOoaQnTyYa_cjRlLFCnxIxtjECFlbKSS8Q:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIjp7ImNydiI6IkVkMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiOTFScmJuMFNmSjBJSExLbU5vamhOVmYxeXhfdlk1YXhtLVp3dGR5V0FXMCJ9LCJwdXJwb3NlcyI6WyJhdXRoZW50aWNhdGlvbiJdLCJ0eXBlIjoiSnNvbldlYktleTIwMjAifV0sInNlcnZpY2VzIjpbeyJpZCI6InBmaSIsInNlcnZpY2VFbmRwb2ludCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsInR5cGUiOiJQRkkifV19fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUR2YzZsUXVUNzQ2MXg4bnBpMTctbEI1Vzd6TlZHaHpSLS01bGhiWlg1SEZnIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlDdjd4QjBXTG1pcTlhVjZsbnFtcjNrS3JSbHlSY1dtdzdNNk1ycXVmRm1TZyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpRDJPRE5JTjI0Smg4WFhQVU9qNmVVRmdHWWg2dGstZmI5TG9zSXRvaVVrQWcifX0",
      "kind": "offering",
      "id": "offering_01hdertt3xemp8t1t51qrt8de3",
      "createdAt": "2023-10-23T17:20:30.333Z"
    },
    "data": {
      "description": "fake offering 1",
      "payoutUnitsPerPayinUnit": "0.0069",
      "payoutCurrency": {
        "currencyCode": "KES"
      },
      "payinCurrency": {
        "currencyCode": "USD"
      },
      "payinMethods": [
        {
          "kind": "USD_LEDGER",
          "requiredPaymentDetails": {}
        }
      ],
      "payoutMethods": [
        {
          "kind": "MOMO_MPESA",
          "requiredPaymentDetails": {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "Mobile Money Required Payment Details",
            "type": "object",
            "required": [
              "phoneNumber",
              "reason"
            ],
            "additionalProperties": false,
            "properties": {
              "phoneNumber": {
                "title": "Mobile money phone number",
                "description": "Phone number of the Mobile Money account",
                "type": "string"
              },
              "reason": {
                "title": "Reason for sending",
                "description": "To abide by the travel rules and financial reporting requirements, the reason for sending money",
                "type": "string"
              }
            }
          }
        },
        {
          "kind": "BANK_FIRSTBANK",
          "requiredPaymentDetails": {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "Bank Transfer Required Payment Details",
            "type": "object",
            "required": [
              "accountNumber",
              "reason"
            ],
            "additionalProperties": false,
            "properties": {
              "accountNumber": {
                "title": "Bank account number",
                "description": "Bank account of the recipient's bank account",
                "type": "string"
              },
              "reason": {
                "title": "Reason for sending",
                "description": "To abide by the travel rules and financial reporting requirements, the reason for sending money",
                "type": "string"
              }
            }
          }
        }
      ],
      "requiredClaims": {
        "id": "7ce4004c-3c38-4853-968b-e411bafcd945",
        "input_descriptors": [
          {
            "id": "bbdb9b7c-5754-4f46-b63b-590bada959e0",
            "constraints": {
              "fields": [
                {
                  "path": [
                    "${'$'}.issuer"
                  ],
                  "filter": {
                    "type": "string",
                    "const": "did:key:z6MkhVUvUEdEbFpQgRyqLryBfE3frxuEyNsqWUmhm2FoKhpp"
                  }
                },
                {
                  "path": [
                    "${'$'}.type"
                  ],
                  "filter": {
                    "type": "string",
                    "const": "SanctionCredential"
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "signature": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDppb246RWlCWjRKclVDdERiY09vYVFuVHlZYV9jalJsTEZDbnhJeHRqRUNGbGJLU1M4UTpleUprWld4MFlTSTZleUp3WVhSamFHVnpJanBiZXlKaFkzUnBiMjRpT2lKeVpYQnNZV05sSWl3aVpHOWpkVzFsYm5RaU9uc2ljSFZpYkdsalMyVjVjeUk2VzNzaWFXUWlPaUprZDI0dGMybG5JaXdpY0hWaWJHbGpTMlY1U25kcklqcDdJbU55ZGlJNklrVmtNalUxTVRraUxDSnJkSGtpT2lKUFMxQWlMQ0o0SWpvaU9URlNjbUp1TUZObVNqQkpTRXhMYlU1dmFtaE9WbVl4ZVhoZmRsazFZWGh0TFZwM2RHUjVWMEZYTUNKOUxDSndkWEp3YjNObGN5STZXeUpoZFhSb1pXNTBhV05oZEdsdmJpSmRMQ0owZVhCbElqb2lTbk52YmxkbFlrdGxlVEl3TWpBaWZWMHNJbk5sY25acFkyVnpJanBiZXlKcFpDSTZJbkJtYVNJc0luTmxjblpwWTJWRmJtUndiMmx1ZENJNkltaDBkSEE2THk5c2IyTmhiR2h2YzNRNk9UQXdNQ0lzSW5SNWNHVWlPaUpRUmtraWZWMTlmVjBzSW5Wd1pHRjBaVU52YlcxcGRHMWxiblFpT2lKRmFVUjJZelpzVVhWVU56UTJNWGc0Ym5CcE1UY3RiRUkxVnpkNlRsWkhhSHBTTFMwMWJHaGlXbGcxU0VabkluMHNJbk4xWm1acGVFUmhkR0VpT25zaVpHVnNkR0ZJWVhOb0lqb2lSV2xEZGpkNFFqQlhURzFwY1RsaFZqWnNibkZ0Y2pOclMzSlNiSGxTWTFkdGR6ZE5OazF5Y1hWbVJtMVRaeUlzSW5KbFkyOTJaWEo1UTI5dGJXbDBiV1Z1ZENJNklrVnBSREpQUkU1SlRqSTBTbWc0V0ZoUVZVOXFObVZWUm1kSFdXZzJkR3N0Wm1JNVRHOXpTWFJ2YVZWclFXY2lmWDAjZHduLXNpZyJ9..wHGxKKMRou9LsODLAJcFs2KMs3iNUYVCpRwUKEQCs5-dB_EZKNEDAmQ63QMVsPPGJp2rjRXCgQlWsBT6R7dOAQ"
  }
```

**Comment by KendallWeihe** [comment]
Here is the DID Doc for that example 

```json
{
  "id": "did:ion:EiB5CXqZ7YFn4cL08ngGlULq3octQda-rlOuwKnGAus6vA:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIjp7ImNydiI6IkVkMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiUDVWLThlQ05uNFFJa1BLdDBkMXJnLTVsdHNUankxa05PVmgzR1VqTHpuSSJ9LCJwdXJwb3NlcyI6WyJhdXRoZW50aWNhdGlvbiJdLCJ0eXBlIjoiSnNvbldlYktleTIwMjAifV0sInNlcnZpY2VzIjpbeyJpZCI6InBmaSIsInNlcnZpY2VFbmRwb2ludCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsInR5cGUiOiJQRkkifV19fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUQtLVF2Q2lDZ0k4X0NsQTFQYkpxOU5RZjZTTXFocWlTeE00UThoQ19rWkJnIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlBSnhQRFV6NjN1dng0b1k5Vkh0Nko3QmotdGhoRG1xQnBNdExsVjZ1T0pZdyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpQWlqSDB5Z2R0TGhlMkFFQkpxZ3g1aFFKeVNQNXR1RnlFMUpPQUczNUhxQ2cifX0",
  "@context": [
    "https://www.w3.org/ns/did/v1",
    {
      "@base": "did:ion:EiB5CXqZ7YFn4cL08ngGlULq3octQda-rlOuwKnGAus6vA:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIjp7ImNydiI6IkVkMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiUDVWLThlQ05uNFFJa1BLdDBkMXJnLTVsdHNUankxa05PVmgzR1VqTHpuSSJ9LCJwdXJwb3NlcyI6WyJhdXRoZW50aWNhdGlvbiJdLCJ0eXBlIjoiSnNvbldlYktleTIwMjAifV0sInNlcnZpY2VzIjpbeyJpZCI6InBmaSIsInNlcnZpY2VFbmRwb2ludCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsInR5cGUiOiJQRkkifV19fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUQtLVF2Q2lDZ0k4X0NsQTFQYkpxOU5RZjZTTXFocWlTeE00UThoQ19rWkJnIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlBSnhQRFV6NjN1dng0b1k5Vkh0Nko3QmotdGhoRG1xQnBNdExsVjZ1T0pZdyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpQWlqSDB5Z2R0TGhlMkFFQkpxZ3g1aFFKeVNQNXR1RnlFMUpPQUczNUhxQ2cifX0"
    }
  ],
  "service": [
    {
      "id": "#pfi",
      "type": "PFI",
      "serviceEndpoint": "http://localhost:9000"
    }
  ],
  "verificationMethod": [
    {
      "id": "#dwn-sig",
      "controller": "did:ion:EiB5CXqZ7YFn4cL08ngGlULq3octQda-rlOuwKnGAus6vA:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIjp7ImNydiI6IkVkMjU1MTkiLCJrdHkiOiJPS1AiLCJ4IjoiUDVWLThlQ05uNFFJa1BLdDBkMXJnLTVsdHNUankxa05PVmgzR1VqTHpuSSJ9LCJwdXJwb3NlcyI6WyJhdXRoZW50aWNhdGlvbiJdLCJ0eXBlIjoiSnNvbldlYktleTIwMjAifV0sInNlcnZpY2VzIjpbeyJpZCI6InBmaSIsInNlcnZpY2VFbmRwb2ludCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsInR5cGUiOiJQRkkifV19fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUQtLVF2Q2lDZ0k4X0NsQTFQYkpxOU5RZjZTTXFocWlTeE00UThoQ19rWkJnIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlBSnhQRFV6NjN1dng0b1k5Vkh0Nko3QmotdGhoRG1xQnBNdExsVjZ1T0pZdyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpQWlqSDB5Z2R0TGhlMkFFQkpxZ3g1aFFKeVNQNXR1RnlFMUpPQUczNUhxQ2cifX0",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "crv": "Ed25519",
        "kty": "OKP",
        "x": "P5V-8eCNn4QIkPKt0d1rg-5ltsTjy1kNOVh3GUjLznI"
      }
    }
  ],
  "authentication": [
    "#dwn-sig"
  ]
}
```

**Comment by KendallWeihe** [comment]
I can replace that line of code with...

```kotlin
val assertionMethods = didResolutionResult.didDocument.verificationMethods
```

And it gets past the iteration exception, but then the call to `Crypto.verify()` fails with...

```
java.security.SignatureException: Signature check failed.
	at web5.sdk.crypto.Ed25519.verify(Ed25519.kt:127)
	at web5.sdk.crypto.Signer$DefaultImpls.verify$default(Signer.kt:115)
	at web5.sdk.crypto.Crypto.verify(Crypto.kt:144)
	at tbdex.sdk.protocol.CryptoUtils.verify(CryptoUtils.kt:84)
	at tbdex.sdk.protocol.models.Resource.verify(Resource.kt:64)
```

**Comment by KendallWeihe** [comment]
This might be an interop issue caused by a difference between CBOR-vs-JSC ... we can ignore this until we get that consistent across both JS and KT implementations

**Comment by KendallWeihe** [comment]
oh I see, this is a possible property in a did doc https://www.w3.org/TR/did-core/#assertion

so probs I just need to create a doc with it... or maybe we need to change expectations in the lib?
